import type { Metadata } from "next";
import "./globals.css";
import "../public/font.css";
import Navbar from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "Coffe Website",
  description: "Generated by Paz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
